// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	AccessLog *accessLog
	Group     *group
	GroupMenu *groupMenu
	GroupUser *groupUser
	Menu      *menu
	User      *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AccessLog = &Q.AccessLog
	Group = &Q.Group
	GroupMenu = &Q.GroupMenu
	GroupUser = &Q.GroupUser
	Menu = &Q.Menu
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		AccessLog: newAccessLog(db, opts...),
		Group:     newGroup(db, opts...),
		GroupMenu: newGroupMenu(db, opts...),
		GroupUser: newGroupUser(db, opts...),
		Menu:      newMenu(db, opts...),
		User:      newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AccessLog accessLog
	Group     group
	GroupMenu groupMenu
	GroupUser groupUser
	Menu      menu
	User      user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		AccessLog: q.AccessLog.clone(db),
		Group:     q.Group.clone(db),
		GroupMenu: q.GroupMenu.clone(db),
		GroupUser: q.GroupUser.clone(db),
		Menu:      q.Menu.clone(db),
		User:      q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		AccessLog: q.AccessLog.replaceDB(db),
		Group:     q.Group.replaceDB(db),
		GroupMenu: q.GroupMenu.replaceDB(db),
		GroupUser: q.GroupUser.replaceDB(db),
		Menu:      q.Menu.replaceDB(db),
		User:      q.User.replaceDB(db),
	}
}

type queryCtx struct {
	AccessLog IAccessLogDo
	Group     IGroupDo
	GroupMenu IGroupMenuDo
	GroupUser IGroupUserDo
	Menu      IMenuDo
	User      IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AccessLog: q.AccessLog.WithContext(ctx),
		Group:     q.Group.WithContext(ctx),
		GroupMenu: q.GroupMenu.WithContext(ctx),
		GroupUser: q.GroupUser.WithContext(ctx),
		Menu:      q.Menu.WithContext(ctx),
		User:      q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
