// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccessLog = "access_log"

// AccessLog mapped from table <access_log>
type AccessLog struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	AccessID    string    `gorm:"column:access_id;not null" json:"access_id"`
	UID         int32     `gorm:"column:uid;not null;comment:user.id" json:"uid"`              // user.id
	Method      string    `gorm:"column:method;not null;comment:request method" json:"method"` // request method
	Path        string    `gorm:"column:path;not null;comment:path" json:"path"`               // path
	Header      string    `gorm:"column:header;not null;comment:http headers" json:"header"`   // http headers
	Query       string    `gorm:"column:query;not null;comment:http query" json:"query"`       // http query
	Body        string    `gorm:"column:body;not null;comment:http body" json:"body"`          // http body
	IP          string    `gorm:"column:ip;not null;comment:client ip" json:"ip"`              // client ip
	Response    string    `gorm:"column:response;not null" json:"response"`
	CreatedTime time.Time `gorm:"column:created_time;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
}

// TableName AccessLog's table name
func (*AccessLog) TableName() string {
	return TableNameAccessLog
}
