// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroupUser = "group_user"

// GroupUser mapped from table <group_user>
type GroupUser struct {
	ID  int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	UID int32 `gorm:"column:uid;not null;comment:uid" json:"uid"`                   // uid
	Gid int32 `gorm:"column:gid;not null;comment:group.id" json:"gid"`              // group.id
}

// TableName GroupUser's table name
func (*GroupUser) TableName() string {
	return TableNameGroupUser
}
