// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroupMenu = "group_menu"

// GroupMenu mapped from table <group_menu>
type GroupMenu struct {
	ID  int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	Mid int32 `gorm:"column:mid;not null;comment:menu.id" json:"mid"`               // menu.id
	Gid int32 `gorm:"column:gid;not null;comment:group.id" json:"gid"`              // group.id
}

// TableName GroupMenu's table name
func (*GroupMenu) TableName() string {
	return TableNameGroupMenu
}
