// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null;comment:群组名称" json:"name"`                        // 群组名称
	Status      int32     `gorm:"column:status;not null;default:1;comment:状态（1-正常，0-禁用）" json:"status"` // 状态（1-正常，0-禁用）
	Remark      string    `gorm:"column:remark;not null" json:"remark"`
	CreatedTime time.Time `gorm:"column:created_time;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
