// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;comment:菜单名称" json:"name"`                        // 菜单名称
	URI         string    `gorm:"column:uri;comment:URI地址" json:"uri"`                         // URI地址
	Level       int32     `gorm:"column:level;default:1;comment:节点等级" json:"level"`            // 节点等级
	Pid         int32     `gorm:"column:pid;comment:父节点菜单ID" json:"pid"`                       // 父节点菜单ID
	Icon        string    `gorm:"column:icon;comment:菜单图标" json:"icon"`                        // 菜单图标
	Status      int32     `gorm:"column:status;default:1;comment:状态（0-禁用，1-正常）" json:"status"` // 状态（0-禁用，1-正常）
	Sort        int32     `gorm:"column:sort;default:999;comment:排序" json:"sort"`              // 排序
	Remark      string    `gorm:"column:remark;comment:备注" json:"remark"`                      // 备注
	CreatedTime time.Time `gorm:"column:created_time;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
