// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID         int32     `gorm:"column:uid;primaryKey;autoIncrement:true" json:"uid"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Password    string    `gorm:"column:password;not null" json:"password"`
	Salt        string    `gorm:"column:salt;not null" json:"salt"`
	RealName    string    `gorm:"column:real_name;not null" json:"real_name"`
	Mobile      string    `gorm:"column:mobile;not null" json:"mobile"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Desc        string    `gorm:"column:desc;not null" json:"desc"`
	LoginTime   int32     `gorm:"column:login_time;not null" json:"login_time"`
	PwdWrong    int32     `gorm:"column:pwd_wrong;not null" json:"pwd_wrong"`
	Status      int32     `gorm:"column:status;not null;default:1" json:"status"`
	CreatedTime time.Time `gorm:"column:created_time;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
